// AUTO-GENERATED from 100-day-calendar.csv — do not edit by hand.
export interface RawCalendarDay {
  day: number;
  date: string; // ISO yyyy-mm-dd
  weekday: string;
  week: number;
  phase: string;
  format: string;
  pillar: string;
  workingTitle: string;
  hookLine: string;
  contentBrief: string;
  cta: string;
  stories: string;
  notes: string;
}

export const CALENDAR_100: RawCalendarDay[] = [
  {
    "day": 1,
    "date": "2026-06-16",
    "weekday": "Tue",
    "week": 1,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Trade breakdown (Proof)",
    "workingTitle": "NQ breakdown — Triple A (AAA) setup",
    "hookLine": "Today's NQ trade, frame by frame: the triple a (aaa) setup the tape called early.",
    "contentBrief": "Break down today's cleanest trade through the triple a (aaa) setup lens. Entry, invalidation, exit.",
    "cta": "Follow — I break down a real trade every session",
    "stories": "Behind-the-scenes of your setup / live marking",
    "notes": ""
  },
  {
    "day": 2,
    "date": "2026-06-17",
    "weekday": "Wed",
    "week": 1,
    "phase": "P1 · Ignition",
    "format": "Carousel",
    "pillar": "GEX & options flow (Authority)",
    "workingTitle": "Why NQ rejects the same level",
    "hookLine": "Same level, same time, every morning — it's not random. It's GEX.",
    "contentBrief": "Same level, same time, every morning — it's not random. It's GEX.",
    "cta": "Save this for your next session",
    "stories": "Q&A box: \"Ask me anything about GEX / order flow\"",
    "notes": ""
  },
  {
    "day": 3,
    "date": "2026-06-18",
    "weekday": "Thu",
    "week": 1,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Orderflow / setups (Discovery)",
    "workingTitle": "What is order flow? (the 60-sec version)",
    "hookLine": "Why the chart only shows half the story — and what order flow shows you.",
    "contentBrief": "Why the chart only shows half the story — and what order flow shows you.",
    "cta": "Follow for the order flow no one teaches • Save",
    "stories": "This-or-that: \"Which is harder: entries or exits?\"",
    "notes": ""
  },
  {
    "day": 4,
    "date": "2026-06-19",
    "weekday": "Fri",
    "week": 1,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Risk & psychology (Shareable)",
    "workingTitle": "Asymmetrical R:R",
    "hookLine": "Why I happily lose 6 out of 10 trades — and still win.",
    "contentBrief": "Why I happily lose 6 out of 10 trades — and still win.",
    "cta": "Share with a trader who needs to hear this",
    "stories": "Poll: \"Your biggest leak: revenge / overtrading / no plan?\"",
    "notes": ""
  },
  {
    "day": 5,
    "date": "2026-06-20",
    "weekday": "Sat",
    "week": 1,
    "phase": "P1 · Ignition",
    "format": "Carousel",
    "pillar": "Process & system (Save + Convert)",
    "workingTitle": "My pre-market routine",
    "hookLine": "The exact 4 steps I run before I touch NQ. Steal it.",
    "contentBrief": "The exact 4 steps I run before I touch NQ. Steal it.",
    "cta": "Save this for your next session",
    "stories": "Lead-magnet sticker + weekend deep-dive teaser",
    "notes": ""
  },
  {
    "day": 6,
    "date": "2026-06-21",
    "weekday": "Sun",
    "week": 1,
    "phase": "P1 · Ignition",
    "format": "Story only",
    "pillar": "Rest · Repurpose · Review",
    "workingTitle": "Weekly review + repurpose top performer",
    "hookLine": "",
    "contentBrief": "Pull your top 3 posts by reach this week, find the pattern, re-share the best to Stories.",
    "cta": "Weekly recap + \"What should I cover next?\" poll",
    "stories": "Recap carousel/story + \"Next week I'm covering ___\" poll",
    "notes": ""
  },
  {
    "day": 7,
    "date": "2026-06-22",
    "weekday": "Mon",
    "week": 1,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Orderflow basics (Discovery)",
    "workingTitle": "Value Area explained",
    "hookLine": "Why price keeps returning to the same zone — Value Area, simply.",
    "contentBrief": "Why price keeps returning to the same zone — Value Area, simply.",
    "cta": "Follow for daily NQ order flow • Save this",
    "stories": "Poll: \"Do you trade order flow? Y/N\"",
    "notes": ""
  },
  {
    "day": 8,
    "date": "2026-06-23",
    "weekday": "Tue",
    "week": 2,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Trade breakdown (Proof)",
    "workingTitle": "NQ breakdown — Trend-following entry",
    "hookLine": "Today's NQ trade, frame by frame: the trend-following entry the tape called early.",
    "contentBrief": "Break down today's cleanest trade through the trend-following entry lens. Entry, invalidation, exit.",
    "cta": "Follow — I break down a real trade every session",
    "stories": "Behind-the-scenes of your setup / live marking",
    "notes": ""
  },
  {
    "day": 9,
    "date": "2026-06-24",
    "weekday": "Wed",
    "week": 2,
    "phase": "P1 · Ignition",
    "format": "Carousel",
    "pillar": "GEX & options flow (Authority)",
    "workingTitle": "Balanced vs imbalanced days",
    "hookLine": "How to tell if the market wants to range or run.",
    "contentBrief": "How to tell if the market wants to range or run.",
    "cta": "Save this for your next session",
    "stories": "Q&A box: \"Ask me anything about GEX / order flow\"",
    "notes": ""
  },
  {
    "day": 10,
    "date": "2026-06-25",
    "weekday": "Thu",
    "week": 2,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Orderflow / setups (Discovery)",
    "workingTitle": "Point of Control (POC)",
    "hookLine": "The single price the whole market agreed on yesterday — and why it matters today.",
    "contentBrief": "The single price the whole market agreed on yesterday — and why it matters today.",
    "cta": "Follow for the order flow no one teaches • Save",
    "stories": "This-or-that: \"Which is harder: entries or exits?\"",
    "notes": ""
  },
  {
    "day": 11,
    "date": "2026-06-26",
    "weekday": "Fri",
    "week": 2,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Risk & psychology (Shareable)",
    "workingTitle": "Stop-loss discipline",
    "hookLine": "The one rule that stopped me blowing accounts.",
    "contentBrief": "The one rule that stopped me blowing accounts.",
    "cta": "Share with a trader who needs to hear this",
    "stories": "Poll: \"Your biggest leak: revenge / overtrading / no plan?\"",
    "notes": ""
  },
  {
    "day": 12,
    "date": "2026-06-27",
    "weekday": "Sat",
    "week": 2,
    "phase": "P1 · Ignition",
    "format": "Carousel",
    "pillar": "Process & system (Save + Convert)",
    "workingTitle": "1-page pre-entry checklist",
    "hookLine": "The checklist I run before every single entry.",
    "contentBrief": "The checklist I run before every single entry.",
    "cta": "Save this for your next session",
    "stories": "Lead-magnet sticker + weekend deep-dive teaser",
    "notes": ""
  },
  {
    "day": 13,
    "date": "2026-06-28",
    "weekday": "Sun",
    "week": 2,
    "phase": "P1 · Ignition",
    "format": "Story only",
    "pillar": "Rest · Repurpose · Review",
    "workingTitle": "Weekly review + repurpose top performer",
    "hookLine": "",
    "contentBrief": "Pull your top 3 posts by reach this week, find the pattern, re-share the best to Stories.",
    "cta": "Weekly recap + \"What should I cover next?\" poll",
    "stories": "Recap carousel/story + \"Next week I'm covering ___\" poll",
    "notes": ""
  },
  {
    "day": 14,
    "date": "2026-06-29",
    "weekday": "Mon",
    "week": 2,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Orderflow basics (Discovery)",
    "workingTitle": "Volume Delta in 60 seconds",
    "hookLine": "Green candle, red delta? Here's what's really happening.",
    "contentBrief": "Green candle, red delta? Here's what's really happening.",
    "cta": "Follow for daily NQ order flow • Save this",
    "stories": "Poll: \"Do you trade order flow? Y/N\"",
    "notes": ""
  },
  {
    "day": 15,
    "date": "2026-06-30",
    "weekday": "Tue",
    "week": 3,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Trade breakdown (Proof)",
    "workingTitle": "NQ breakdown — Mean-reversion at value edge",
    "hookLine": "Today's NQ trade, frame by frame: the mean-reversion at value edge the tape called early.",
    "contentBrief": "Break down today's cleanest trade through the mean-reversion at value edge lens. Entry, invalidation, exit.",
    "cta": "Follow — I break down a real trade every session",
    "stories": "Behind-the-scenes of your setup / live marking",
    "notes": ""
  },
  {
    "day": 16,
    "date": "2026-07-01",
    "weekday": "Wed",
    "week": 3,
    "phase": "P1 · Ignition",
    "format": "Carousel",
    "pillar": "GEX & options flow (Authority)",
    "workingTitle": "Gamma walls",
    "hookLine": "Invisible support & resistance the options market draws for you.",
    "contentBrief": "Invisible support & resistance the options market draws for you.",
    "cta": "Save this for your next session",
    "stories": "Q&A box: \"Ask me anything about GEX / order flow\"",
    "notes": ""
  },
  {
    "day": 17,
    "date": "2026-07-02",
    "weekday": "Thu",
    "week": 3,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Orderflow / setups (Discovery)",
    "workingTitle": "Absorption",
    "hookLine": "When price hits a wall and big players eat every sell — that's absorption.",
    "contentBrief": "When price hits a wall and big players eat every sell — that's absorption.",
    "cta": "Follow for the order flow no one teaches • Save",
    "stories": "This-or-that: \"Which is harder: entries or exits?\"",
    "notes": ""
  },
  {
    "day": 18,
    "date": "2026-07-03",
    "weekday": "Fri",
    "week": 3,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Risk & psychology (Shareable)",
    "workingTitle": "Trailing profits",
    "hookLine": "How to ride a winner without choking it to death.",
    "contentBrief": "How to ride a winner without choking it to death.",
    "cta": "Share with a trader who needs to hear this",
    "stories": "Poll: \"Your biggest leak: revenge / overtrading / no plan?\"",
    "notes": ""
  },
  {
    "day": 19,
    "date": "2026-07-04",
    "weekday": "Sat",
    "week": 3,
    "phase": "P1 · Ignition",
    "format": "Carousel",
    "pillar": "Process & system (Save + Convert)",
    "workingTitle": "How I journal in 5 min",
    "hookLine": "The 5-minute journal that doubled my consistency.",
    "contentBrief": "The 5-minute journal that doubled my consistency.",
    "cta": "Comment \"TAPE\" and I'll DM you the free cheat sheet",
    "stories": "Lead-magnet sticker + weekend deep-dive teaser",
    "notes": ""
  },
  {
    "day": 20,
    "date": "2026-07-05",
    "weekday": "Sun",
    "week": 3,
    "phase": "P1 · Ignition",
    "format": "Story only",
    "pillar": "Rest · Repurpose · Review",
    "workingTitle": "Weekly review + repurpose top performer",
    "hookLine": "",
    "contentBrief": "Pull your top 3 posts by reach this week, find the pattern, re-share the best to Stories.",
    "cta": "Weekly recap + \"What should I cover next?\" poll",
    "stories": "Recap carousel/story + \"Next week I'm covering ___\" poll",
    "notes": ""
  },
  {
    "day": 21,
    "date": "2026-07-06",
    "weekday": "Mon",
    "week": 3,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Orderflow basics (Discovery)",
    "workingTitle": "Aggressive vs passive orders",
    "hookLine": "Who actually moves price: the people hitting market, not the ones waiting.",
    "contentBrief": "Who actually moves price: the people hitting market, not the ones waiting.",
    "cta": "Follow for daily NQ order flow • Save this",
    "stories": "Poll: \"Do you trade order flow? Y/N\"",
    "notes": ""
  },
  {
    "day": 22,
    "date": "2026-07-07",
    "weekday": "Tue",
    "week": 4,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Trade breakdown (Proof)",
    "workingTitle": "NQ breakdown — Squeeze play",
    "hookLine": "Today's NQ trade, frame by frame: the squeeze play the tape called early.",
    "contentBrief": "Break down today's cleanest trade through the squeeze play lens. Entry, invalidation, exit.",
    "cta": "Follow — I break down a real trade every session",
    "stories": "Behind-the-scenes of your setup / live marking",
    "notes": ""
  },
  {
    "day": 23,
    "date": "2026-07-08",
    "weekday": "Wed",
    "week": 4,
    "phase": "P1 · Ignition",
    "format": "Carousel",
    "pillar": "GEX & options flow (Authority)",
    "workingTitle": "Choppy / decisional days",
    "hookLine": "Survive them, don't force them — the rules that save your week.",
    "contentBrief": "Survive them, don't force them — the rules that save your week.",
    "cta": "Save this for your next session",
    "stories": "Q&A box: \"Ask me anything about GEX / order flow\"",
    "notes": ""
  },
  {
    "day": 24,
    "date": "2026-07-09",
    "weekday": "Thu",
    "week": 4,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Orderflow / setups (Discovery)",
    "workingTitle": "Support & resistance is lying",
    "hookLine": "Why your S/R lines fail — and what order flow uses instead.",
    "contentBrief": "Why your S/R lines fail — and what order flow uses instead.",
    "cta": "Follow for the order flow no one teaches • Save",
    "stories": "This-or-that: \"Which is harder: entries or exits?\"",
    "notes": ""
  },
  {
    "day": 25,
    "date": "2026-07-10",
    "weekday": "Fri",
    "week": 4,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Risk & psychology (Shareable)",
    "workingTitle": "Daily loss limit",
    "hookLine": "My hard line. Hit it, laptop closed. No exceptions.",
    "contentBrief": "My hard line. Hit it, laptop closed. No exceptions.",
    "cta": "Share with a trader who needs to hear this",
    "stories": "Poll: \"Your biggest leak: revenge / overtrading / no plan?\"",
    "notes": ""
  },
  {
    "day": 26,
    "date": "2026-07-11",
    "weekday": "Sat",
    "week": 4,
    "phase": "P1 · Ignition",
    "format": "Carousel",
    "pillar": "Process & system (Save + Convert)",
    "workingTitle": "My NQ playbook (free)",
    "hookLine": "The full framework I trade — turned into a free cheat sheet.",
    "contentBrief": "The full framework I trade — turned into a free cheat sheet.",
    "cta": "Comment \"PLAYBOOK\" and I'll DM you the free cheat sheet",
    "stories": "Lead-magnet sticker + weekend deep-dive teaser",
    "notes": ""
  },
  {
    "day": 27,
    "date": "2026-07-12",
    "weekday": "Sun",
    "week": 4,
    "phase": "P1 · Ignition",
    "format": "Story only",
    "pillar": "Rest · Repurpose · Review",
    "workingTitle": "Weekly review + repurpose top performer",
    "hookLine": "",
    "contentBrief": "Pull your top 3 posts by reach this week, find the pattern, re-share the best to Stories.",
    "cta": "Weekly recap + \"What should I cover next?\" poll",
    "stories": "Recap carousel/story + \"Next week I'm covering ___\" poll",
    "notes": "MONTH REVIEW: check reach-from-non-followers %, saves, shares, profile-visit→follow"
  },
  {
    "day": 28,
    "date": "2026-07-13",
    "weekday": "Mon",
    "week": 4,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Orderflow basics (Discovery)",
    "workingTitle": "The footprint chart",
    "hookLine": "How to read a footprint candle without drowning in numbers.",
    "contentBrief": "How to read a footprint candle without drowning in numbers.",
    "cta": "Follow for daily NQ order flow • Save this",
    "stories": "Poll: \"Do you trade order flow? Y/N\"",
    "notes": ""
  },
  {
    "day": 29,
    "date": "2026-07-14",
    "weekday": "Tue",
    "week": 5,
    "phase": "P1 · Ignition",
    "format": "Reel",
    "pillar": "Trade breakdown (Proof)",
    "workingTitle": "NQ breakdown — ORB + IVB filter",
    "hookLine": "Today's NQ trade, frame by frame: the orb + ivb filter the tape called early.",
    "contentBrief": "Break down today's cleanest trade through the orb + ivb filter lens. Entry, invalidation, exit.",
    "cta": "Follow — I break down a real trade every session",
    "stories": "Behind-the-scenes of your setup / live marking",
    "notes": ""
  },
  {
    "day": 30,
    "date": "2026-07-15",
    "weekday": "Wed",
    "week": 5,
    "phase": "P1 · Ignition",
    "format": "Carousel",
    "pillar": "GEX & options flow (Authority)",
    "workingTitle": "The gamma flip",
    "hookLine": "The one line that flips NQ from calm to violent — no math degree needed.",
    "contentBrief": "The one line that flips NQ from calm to violent — no math degree needed.",
    "cta": "Save this for your next session",
    "stories": "Q&A box: \"Ask me anything about GEX / order flow\"",
    "notes": ""
  },
  {
    "day": 31,
    "date": "2026-07-16",
    "weekday": "Thu",
    "week": 5,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Orderflow / setups (Discovery)",
    "workingTitle": "CVD (cumulative volume delta)",
    "hookLine": "Following the real buying pressure under the price.",
    "contentBrief": "Following the real buying pressure under the price.",
    "cta": "Follow for the order flow no one teaches • Save",
    "stories": "This-or-that: \"Which is harder: entries or exits?\"",
    "notes": ""
  },
  {
    "day": 32,
    "date": "2026-07-17",
    "weekday": "Fri",
    "week": 5,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Risk & psychology (Shareable)",
    "workingTitle": "Size down on chop",
    "hookLine": "The expensive lesson: small size on decisional days.",
    "contentBrief": "The expensive lesson: small size on decisional days.",
    "cta": "Share with a trader who needs to hear this",
    "stories": "Poll: \"Your biggest leak: revenge / overtrading / no plan?\"",
    "notes": ""
  },
  {
    "day": 33,
    "date": "2026-07-18",
    "weekday": "Sat",
    "week": 5,
    "phase": "P2 · Authority",
    "format": "Carousel",
    "pillar": "Process & system (Save + Convert)",
    "workingTitle": "How I plan the week",
    "hookLine": "Sunday prep so the week trades itself.",
    "contentBrief": "Sunday prep so the week trades itself.",
    "cta": "Comment \"TAPE\" and I'll DM you the free cheat sheet",
    "stories": "Lead-magnet sticker + weekend deep-dive teaser",
    "notes": ""
  },
  {
    "day": 34,
    "date": "2026-07-19",
    "weekday": "Sun",
    "week": 5,
    "phase": "P2 · Authority",
    "format": "Story only",
    "pillar": "Rest · Repurpose · Review",
    "workingTitle": "Weekly review + repurpose top performer",
    "hookLine": "",
    "contentBrief": "Pull your top 3 posts by reach this week, find the pattern, re-share the best to Stories.",
    "cta": "Weekly recap + \"What should I cover next?\" poll",
    "stories": "Recap carousel/story + \"Next week I'm covering ___\" poll",
    "notes": ""
  },
  {
    "day": 35,
    "date": "2026-07-20",
    "weekday": "Mon",
    "week": 5,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Orderflow basics (Discovery)",
    "workingTitle": "Initial Balance",
    "hookLine": "The first hour writes the day's script — here's how to read it.",
    "contentBrief": "The first hour writes the day's script — here's how to read it.",
    "cta": "Follow for daily NQ order flow • Save this",
    "stories": "Poll: \"Do you trade order flow? Y/N\"",
    "notes": "COLLAB: DM 2-3 same-size SA trader accounts for a co-Reel / shoutout swap"
  },
  {
    "day": 36,
    "date": "2026-07-21",
    "weekday": "Tue",
    "week": 6,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Trade breakdown (Proof)",
    "workingTitle": "NQ breakdown — Absorption reversal",
    "hookLine": "Today's NQ trade, frame by frame: the absorption reversal the tape called early.",
    "contentBrief": "Break down today's cleanest trade through the absorption reversal lens. Entry, invalidation, exit.",
    "cta": "Follow — I break down a real trade every session",
    "stories": "Behind-the-scenes of your setup / live marking",
    "notes": ""
  },
  {
    "day": 37,
    "date": "2026-07-22",
    "weekday": "Wed",
    "week": 6,
    "phase": "P2 · Authority",
    "format": "Carousel",
    "pillar": "GEX & options flow (Authority)",
    "workingTitle": "NY cash session",
    "hookLine": "Where the real volume lives, and why I trade it.",
    "contentBrief": "Where the real volume lives, and why I trade it.",
    "cta": "Save this for your next session",
    "stories": "Q&A box: \"Ask me anything about GEX / order flow\"",
    "notes": ""
  },
  {
    "day": 38,
    "date": "2026-07-23",
    "weekday": "Thu",
    "week": 6,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Orderflow / setups (Discovery)",
    "workingTitle": "Stacked imbalances",
    "hookLine": "Institutional footprints left in plain sight on the tape.",
    "contentBrief": "Institutional footprints left in plain sight on the tape.",
    "cta": "Follow for the order flow no one teaches • Save",
    "stories": "This-or-that: \"Which is harder: entries or exits?\"",
    "notes": ""
  },
  {
    "day": 39,
    "date": "2026-07-24",
    "weekday": "Fri",
    "week": 6,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Risk & psychology (Shareable)",
    "workingTitle": "Profit recycling",
    "hookLine": "Compounding the right way without getting greedy.",
    "contentBrief": "Compounding the right way without getting greedy.",
    "cta": "Share with a trader who needs to hear this",
    "stories": "Poll: \"Your biggest leak: revenge / overtrading / no plan?\"",
    "notes": ""
  },
  {
    "day": 40,
    "date": "2026-07-25",
    "weekday": "Sat",
    "week": 6,
    "phase": "P2 · Authority",
    "format": "Carousel",
    "pillar": "Process & system (Save + Convert)",
    "workingTitle": "My order flow screen layout",
    "hookLine": "Exactly what's on my charts and why.",
    "contentBrief": "Exactly what's on my charts and why.",
    "cta": "Comment \"TAPE\" and I'll DM you the free cheat sheet",
    "stories": "Lead-magnet sticker + weekend deep-dive teaser",
    "notes": ""
  },
  {
    "day": 41,
    "date": "2026-07-26",
    "weekday": "Sun",
    "week": 6,
    "phase": "P2 · Authority",
    "format": "Story only",
    "pillar": "Rest · Repurpose · Review",
    "workingTitle": "Weekly review + repurpose top performer",
    "hookLine": "",
    "contentBrief": "Pull your top 3 posts by reach this week, find the pattern, re-share the best to Stories.",
    "cta": "Weekly recap + \"What should I cover next?\" poll",
    "stories": "Recap carousel/story + \"Next week I'm covering ___\" poll",
    "notes": ""
  },
  {
    "day": 42,
    "date": "2026-07-27",
    "weekday": "Mon",
    "week": 6,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Orderflow basics (Discovery)",
    "workingTitle": "Liquidity & stop hunts",
    "hookLine": "Where the market hides the stops — and why it runs there first.",
    "contentBrief": "Where the market hides the stops — and why it runs there first.",
    "cta": "Follow for daily NQ order flow • Save this",
    "stories": "Poll: \"Do you trade order flow? Y/N\"",
    "notes": "COLLAB: DM 2-3 same-size SA trader accounts for a co-Reel / shoutout swap"
  },
  {
    "day": 43,
    "date": "2026-07-28",
    "weekday": "Tue",
    "week": 7,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Trade breakdown (Proof)",
    "workingTitle": "NQ breakdown — POC rejection",
    "hookLine": "Today's NQ trade, frame by frame: the poc rejection the tape called early.",
    "contentBrief": "Break down today's cleanest trade through the poc rejection lens. Entry, invalidation, exit.",
    "cta": "Follow — I break down a real trade every session",
    "stories": "Behind-the-scenes of your setup / live marking",
    "notes": ""
  },
  {
    "day": 44,
    "date": "2026-07-29",
    "weekday": "Wed",
    "week": 7,
    "phase": "P2 · Authority",
    "format": "Carousel",
    "pillar": "GEX & options flow (Authority)",
    "workingTitle": "How dealer hedging moves NQ",
    "hookLine": "Why the people you never see are pushing price around.",
    "contentBrief": "Why the people you never see are pushing price around.",
    "cta": "Save this for your next session",
    "stories": "Q&A box: \"Ask me anything about GEX / order flow\"",
    "notes": ""
  },
  {
    "day": 45,
    "date": "2026-07-30",
    "weekday": "Thu",
    "week": 7,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Orderflow / setups (Discovery)",
    "workingTitle": "Single-day profiling",
    "hookLine": "Reading one session's whole story in one shape.",
    "contentBrief": "Reading one session's whole story in one shape.",
    "cta": "Follow for the order flow no one teaches • Save",
    "stories": "This-or-that: \"Which is harder: entries or exits?\"",
    "notes": ""
  },
  {
    "day": 46,
    "date": "2026-07-31",
    "weekday": "Fri",
    "week": 7,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Risk & psychology (Shareable)",
    "workingTitle": "The trade that blew my account",
    "hookLine": "My first funded account, gone in one afternoon. The lesson stuck.",
    "contentBrief": "My first funded account, gone in one afternoon. The lesson stuck.",
    "cta": "Share with a trader who needs to hear this",
    "stories": "Poll: \"Your biggest leak: revenge / overtrading / no plan?\"",
    "notes": ""
  },
  {
    "day": 47,
    "date": "2026-08-01",
    "weekday": "Sat",
    "week": 7,
    "phase": "P2 · Authority",
    "format": "Carousel",
    "pillar": "Process & system (Save + Convert)",
    "workingTitle": "My pre-market routine",
    "hookLine": "The exact 4 steps I run before I touch NQ. Steal it.",
    "contentBrief": "The exact 4 steps I run before I touch NQ. Steal it.",
    "cta": "Comment \"ROUTINE\" and I'll DM you the free cheat sheet",
    "stories": "Lead-magnet sticker + weekend deep-dive teaser",
    "notes": ""
  },
  {
    "day": 48,
    "date": "2026-08-02",
    "weekday": "Sun",
    "week": 7,
    "phase": "P2 · Authority",
    "format": "Story only",
    "pillar": "Rest · Repurpose · Review",
    "workingTitle": "Weekly review + repurpose top performer",
    "hookLine": "",
    "contentBrief": "Pull your top 3 posts by reach this week, find the pattern, re-share the best to Stories.",
    "cta": "Weekly recap + \"What should I cover next?\" poll",
    "stories": "Recap carousel/story + \"Next week I'm covering ___\" poll",
    "notes": ""
  },
  {
    "day": 49,
    "date": "2026-08-03",
    "weekday": "Mon",
    "week": 7,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Orderflow basics (Discovery)",
    "workingTitle": "Composite profiles",
    "hookLine": "Zooming out: the bigger map most retail traders ignore.",
    "contentBrief": "Zooming out: the bigger map most retail traders ignore.",
    "cta": "Follow for daily NQ order flow • Save this",
    "stories": "Poll: \"Do you trade order flow? Y/N\"",
    "notes": "COLLAB: DM 2-3 same-size SA trader accounts for a co-Reel / shoutout swap"
  },
  {
    "day": 50,
    "date": "2026-08-04",
    "weekday": "Tue",
    "week": 8,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Trade breakdown (Proof)",
    "workingTitle": "NQ breakdown — Gamma-level fade",
    "hookLine": "Today's NQ trade, frame by frame: the gamma-level fade the tape called early.",
    "contentBrief": "Break down today's cleanest trade through the gamma-level fade lens. Entry, invalidation, exit.",
    "cta": "Follow — I break down a real trade every session",
    "stories": "Behind-the-scenes of your setup / live marking",
    "notes": ""
  },
  {
    "day": 51,
    "date": "2026-08-05",
    "weekday": "Wed",
    "week": 8,
    "phase": "P2 · Authority",
    "format": "Carousel",
    "pillar": "GEX & options flow (Authority)",
    "workingTitle": "London session edge",
    "hookLine": "The slower, cleaner setups before New York wakes up.",
    "contentBrief": "The slower, cleaner setups before New York wakes up.",
    "cta": "Save this for your next session",
    "stories": "Q&A box: \"Ask me anything about GEX / order flow\"",
    "notes": ""
  },
  {
    "day": 52,
    "date": "2026-08-06",
    "weekday": "Thu",
    "week": 8,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Orderflow / setups (Discovery)",
    "workingTitle": "Trend day vs chop day",
    "hookLine": "Spotting the day type in the first 30 minutes.",
    "contentBrief": "Spotting the day type in the first 30 minutes.",
    "cta": "Follow for the order flow no one teaches • Save",
    "stories": "This-or-that: \"Which is harder: entries or exits?\"",
    "notes": ""
  },
  {
    "day": 53,
    "date": "2026-08-07",
    "weekday": "Fri",
    "week": 8,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Risk & psychology (Shareable)",
    "workingTitle": "Ego management",
    "hookLine": "The strongest trade you'll make is the one you DON'T take.",
    "contentBrief": "The strongest trade you'll make is the one you DON'T take.",
    "cta": "Share with a trader who needs to hear this",
    "stories": "Poll: \"Your biggest leak: revenge / overtrading / no plan?\"",
    "notes": ""
  },
  {
    "day": 54,
    "date": "2026-08-08",
    "weekday": "Sat",
    "week": 8,
    "phase": "P2 · Authority",
    "format": "Carousel",
    "pillar": "Process & system (Save + Convert)",
    "workingTitle": "1-page pre-entry checklist",
    "hookLine": "The checklist I run before every single entry.",
    "contentBrief": "The checklist I run before every single entry.",
    "cta": "Comment \"TAPE\" and I'll DM you the free cheat sheet",
    "stories": "Lead-magnet sticker + weekend deep-dive teaser",
    "notes": ""
  },
  {
    "day": 55,
    "date": "2026-08-09",
    "weekday": "Sun",
    "week": 8,
    "phase": "P2 · Authority",
    "format": "Story only",
    "pillar": "Rest · Repurpose · Review",
    "workingTitle": "Weekly review + repurpose top performer",
    "hookLine": "",
    "contentBrief": "Pull your top 3 posts by reach this week, find the pattern, re-share the best to Stories.",
    "cta": "Weekly recap + \"What should I cover next?\" poll",
    "stories": "Recap carousel/story + \"Next week I'm covering ___\" poll",
    "notes": "MONTH REVIEW: check reach-from-non-followers %, saves, shares, profile-visit→follow"
  },
  {
    "day": 56,
    "date": "2026-08-10",
    "weekday": "Mon",
    "week": 8,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Orderflow basics (Discovery)",
    "workingTitle": "Opening Range Breakout (ORB)",
    "hookLine": "The simplest session-open playbook, done right.",
    "contentBrief": "The simplest session-open playbook, done right.",
    "cta": "Follow for daily NQ order flow • Save this",
    "stories": "Poll: \"Do you trade order flow? Y/N\"",
    "notes": "COLLAB: DM 2-3 same-size SA trader accounts for a co-Reel / shoutout swap"
  },
  {
    "day": 57,
    "date": "2026-08-11",
    "weekday": "Tue",
    "week": 9,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Trade breakdown (Proof)",
    "workingTitle": "NQ breakdown — Failed breakout trap",
    "hookLine": "Today's NQ trade, frame by frame: the failed breakout trap the tape called early.",
    "contentBrief": "Break down today's cleanest trade through the failed breakout trap lens. Entry, invalidation, exit.",
    "cta": "Follow — I break down a real trade every session",
    "stories": "Behind-the-scenes of your setup / live marking",
    "notes": ""
  },
  {
    "day": 58,
    "date": "2026-08-12",
    "weekday": "Wed",
    "week": 9,
    "phase": "P2 · Authority",
    "format": "Carousel",
    "pillar": "GEX & options flow (Authority)",
    "workingTitle": "Positive vs negative gamma days",
    "hookLine": "Same chart, two completely different playbooks.",
    "contentBrief": "Same chart, two completely different playbooks.",
    "cta": "Save this for your next session",
    "stories": "Q&A box: \"Ask me anything about GEX / order flow\"",
    "notes": ""
  },
  {
    "day": 59,
    "date": "2026-08-13",
    "weekday": "Thu",
    "week": 9,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Orderflow / setups (Discovery)",
    "workingTitle": "Deep Effort / effort vs result",
    "hookLine": "When the market tries hard and goes nowhere — read it.",
    "contentBrief": "When the market tries hard and goes nowhere — read it.",
    "cta": "Follow for the order flow no one teaches • Save",
    "stories": "This-or-that: \"Which is harder: entries or exits?\"",
    "notes": ""
  },
  {
    "day": 60,
    "date": "2026-08-14",
    "weekday": "Fri",
    "week": 9,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Risk & psychology (Shareable)",
    "workingTitle": "Accepting losses",
    "hookLine": "Losses aren't failure — they're the cost of doing business.",
    "contentBrief": "Losses aren't failure — they're the cost of doing business.",
    "cta": "Share with a trader who needs to hear this",
    "stories": "Poll: \"Your biggest leak: revenge / overtrading / no plan?\"",
    "notes": ""
  },
  {
    "day": 61,
    "date": "2026-08-15",
    "weekday": "Sat",
    "week": 9,
    "phase": "P2 · Authority",
    "format": "Carousel",
    "pillar": "Process & system (Save + Convert)",
    "workingTitle": "How I journal in 5 min",
    "hookLine": "The 5-minute journal that doubled my consistency.",
    "contentBrief": "The 5-minute journal that doubled my consistency.",
    "cta": "Comment \"TAPE\" and I'll DM you the free cheat sheet",
    "stories": "Lead-magnet sticker + weekend deep-dive teaser",
    "notes": ""
  },
  {
    "day": 62,
    "date": "2026-08-16",
    "weekday": "Sun",
    "week": 9,
    "phase": "P2 · Authority",
    "format": "Story only",
    "pillar": "Rest · Repurpose · Review",
    "workingTitle": "Weekly review + repurpose top performer",
    "hookLine": "",
    "contentBrief": "Pull your top 3 posts by reach this week, find the pattern, re-share the best to Stories.",
    "cta": "Weekly recap + \"What should I cover next?\" poll",
    "stories": "Recap carousel/story + \"Next week I'm covering ___\" poll",
    "notes": ""
  },
  {
    "day": 63,
    "date": "2026-08-17",
    "weekday": "Mon",
    "week": 9,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Orderflow basics (Discovery)",
    "workingTitle": "IVB (initial volume bias)",
    "hookLine": "The early tell for which side is in control.",
    "contentBrief": "The early tell for which side is in control.",
    "cta": "Follow for daily NQ order flow • Save this",
    "stories": "Poll: \"Do you trade order flow? Y/N\"",
    "notes": "COLLAB: DM 2-3 same-size SA trader accounts for a co-Reel / shoutout swap"
  },
  {
    "day": 64,
    "date": "2026-08-18",
    "weekday": "Tue",
    "week": 10,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Trade breakdown (Proof)",
    "workingTitle": "NQ breakdown — CVD divergence entry",
    "hookLine": "Today's NQ trade, frame by frame: the cvd divergence entry the tape called early.",
    "contentBrief": "Break down today's cleanest trade through the cvd divergence entry lens. Entry, invalidation, exit.",
    "cta": "Follow — I break down a real trade every session",
    "stories": "Behind-the-scenes of your setup / live marking",
    "notes": ""
  },
  {
    "day": 65,
    "date": "2026-08-19",
    "weekday": "Wed",
    "week": 10,
    "phase": "P2 · Authority",
    "format": "Carousel",
    "pillar": "GEX & options flow (Authority)",
    "workingTitle": "Power Hour playbook",
    "hookLine": "The last hour: the trap and the gift.",
    "contentBrief": "The last hour: the trap and the gift.",
    "cta": "Save this for your next session",
    "stories": "Q&A box: \"Ask me anything about GEX / order flow\"",
    "notes": ""
  },
  {
    "day": 66,
    "date": "2026-08-20",
    "weekday": "Thu",
    "week": 10,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Orderflow / setups (Discovery)",
    "workingTitle": "What is order flow? (the 60-sec version)",
    "hookLine": "Why the chart only shows half the story — and what order flow shows you.",
    "contentBrief": "Why the chart only shows half the story — and what order flow shows you.",
    "cta": "Follow for the order flow no one teaches • Save",
    "stories": "This-or-that: \"Which is harder: entries or exits?\"",
    "notes": ""
  },
  {
    "day": 67,
    "date": "2026-08-21",
    "weekday": "Fri",
    "week": 10,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Risk & psychology (Shareable)",
    "workingTitle": "Patience",
    "hookLine": "Waiting for YOUR setup while everyone else overtrades.",
    "contentBrief": "Waiting for YOUR setup while everyone else overtrades.",
    "cta": "Share with a trader who needs to hear this",
    "stories": "Poll: \"Your biggest leak: revenge / overtrading / no plan?\"",
    "notes": ""
  },
  {
    "day": 68,
    "date": "2026-08-22",
    "weekday": "Sat",
    "week": 10,
    "phase": "P2 · Authority",
    "format": "Carousel",
    "pillar": "Process & system (Save + Convert)",
    "workingTitle": "My NQ playbook (free)",
    "hookLine": "The full framework I trade — turned into a free cheat sheet.",
    "contentBrief": "The full framework I trade — turned into a free cheat sheet.",
    "cta": "Comment \"PLAYBOOK\" and I'll DM you the free cheat sheet",
    "stories": "Lead-magnet sticker + weekend deep-dive teaser",
    "notes": ""
  },
  {
    "day": 69,
    "date": "2026-08-23",
    "weekday": "Sun",
    "week": 10,
    "phase": "P2 · Authority",
    "format": "Story only",
    "pillar": "Rest · Repurpose · Review",
    "workingTitle": "Weekly review + repurpose top performer",
    "hookLine": "",
    "contentBrief": "Pull your top 3 posts by reach this week, find the pattern, re-share the best to Stories.",
    "cta": "Weekly recap + \"What should I cover next?\" poll",
    "stories": "Recap carousel/story + \"Next week I'm covering ___\" poll",
    "notes": ""
  },
  {
    "day": 70,
    "date": "2026-08-24",
    "weekday": "Mon",
    "week": 10,
    "phase": "P2 · Authority",
    "format": "Reel",
    "pillar": "Orderflow basics (Discovery)",
    "workingTitle": "Value Area explained",
    "hookLine": "Why price keeps returning to the same zone — Value Area, simply.",
    "contentBrief": "Why price keeps returning to the same zone — Value Area, simply.",
    "cta": "Follow for daily NQ order flow • Save this",
    "stories": "Poll: \"Do you trade order flow? Y/N\"",
    "notes": "COLLAB: DM 2-3 same-size SA trader accounts for a co-Reel / shoutout swap"
  },
  {
    "day": 71,
    "date": "2026-08-25",
    "weekday": "Tue",
    "week": 11,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Trade breakdown (Proof)",
    "workingTitle": "NQ breakdown — Triple A (AAA) setup",
    "hookLine": "Today's NQ trade, frame by frame: the triple a (aaa) setup the tape called early.",
    "contentBrief": "Break down today's cleanest trade through the triple a (aaa) setup lens. Entry, invalidation, exit.",
    "cta": "Follow — I break down a real trade every session",
    "stories": "Behind-the-scenes of your setup / live marking",
    "notes": ""
  },
  {
    "day": 72,
    "date": "2026-08-26",
    "weekday": "Wed",
    "week": 11,
    "phase": "P3 · Compound",
    "format": "Carousel",
    "pillar": "GEX & options flow (Authority)",
    "workingTitle": "Marking gamma levels pre-open",
    "hookLine": "The 3 levels I draw before the bell every day.",
    "contentBrief": "The 3 levels I draw before the bell every day.",
    "cta": "Save this for your next session",
    "stories": "Q&A box: \"Ask me anything about GEX / order flow\"",
    "notes": ""
  },
  {
    "day": 73,
    "date": "2026-08-27",
    "weekday": "Thu",
    "week": 11,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Orderflow / setups (Discovery)",
    "workingTitle": "Point of Control (POC)",
    "hookLine": "The single price the whole market agreed on yesterday — and why it matters today.",
    "contentBrief": "The single price the whole market agreed on yesterday — and why it matters today.",
    "cta": "Follow for the order flow no one teaches • Save",
    "stories": "This-or-that: \"Which is harder: entries or exits?\"",
    "notes": ""
  },
  {
    "day": 74,
    "date": "2026-08-28",
    "weekday": "Fri",
    "week": 11,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Risk & psychology (Shareable)",
    "workingTitle": "3 order flow traps",
    "hookLine": "Three 'signals' that are actually bait — I fell for all of them.",
    "contentBrief": "Three 'signals' that are actually bait — I fell for all of them.",
    "cta": "Share with a trader who needs to hear this",
    "stories": "Poll: \"Your biggest leak: revenge / overtrading / no plan?\"",
    "notes": "CONVERT: pin best lead-magnet reel; mention free Telegram/community in Stories"
  },
  {
    "day": 75,
    "date": "2026-08-29",
    "weekday": "Sat",
    "week": 11,
    "phase": "P3 · Compound",
    "format": "Carousel",
    "pillar": "Process & system (Save + Convert)",
    "workingTitle": "How I plan the week",
    "hookLine": "Sunday prep so the week trades itself.",
    "contentBrief": "Sunday prep so the week trades itself.",
    "cta": "Comment \"TAPE\" and I'll DM you the free cheat sheet",
    "stories": "Lead-magnet sticker + weekend deep-dive teaser",
    "notes": ""
  },
  {
    "day": 76,
    "date": "2026-08-30",
    "weekday": "Sun",
    "week": 11,
    "phase": "P3 · Compound",
    "format": "Story only",
    "pillar": "Rest · Repurpose · Review",
    "workingTitle": "Weekly review + repurpose top performer",
    "hookLine": "",
    "contentBrief": "Pull your top 3 posts by reach this week, find the pattern, re-share the best to Stories.",
    "cta": "Weekly recap + \"What should I cover next?\" poll",
    "stories": "Recap carousel/story + \"Next week I'm covering ___\" poll",
    "notes": ""
  },
  {
    "day": 77,
    "date": "2026-08-31",
    "weekday": "Mon",
    "week": 11,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Orderflow basics (Discovery)",
    "workingTitle": "Volume Delta in 60 seconds",
    "hookLine": "Green candle, red delta? Here's what's really happening.",
    "contentBrief": "Green candle, red delta? Here's what's really happening.",
    "cta": "Follow for daily NQ order flow • Save this",
    "stories": "Poll: \"Do you trade order flow? Y/N\"",
    "notes": ""
  },
  {
    "day": 78,
    "date": "2026-09-01",
    "weekday": "Tue",
    "week": 12,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Trade breakdown (Proof)",
    "workingTitle": "NQ breakdown — Trend-following entry",
    "hookLine": "Today's NQ trade, frame by frame: the trend-following entry the tape called early.",
    "contentBrief": "Break down today's cleanest trade through the trend-following entry lens. Entry, invalidation, exit.",
    "cta": "Follow — I break down a real trade every session",
    "stories": "Behind-the-scenes of your setup / live marking",
    "notes": ""
  },
  {
    "day": 79,
    "date": "2026-09-02",
    "weekday": "Wed",
    "week": 12,
    "phase": "P3 · Compound",
    "format": "Carousel",
    "pillar": "GEX & options flow (Authority)",
    "workingTitle": "Read the day before you trade",
    "hookLine": "My 4-step day-type read I run every morning.",
    "contentBrief": "My 4-step day-type read I run every morning.",
    "cta": "Save this for your next session",
    "stories": "Q&A box: \"Ask me anything about GEX / order flow\"",
    "notes": ""
  },
  {
    "day": 80,
    "date": "2026-09-03",
    "weekday": "Thu",
    "week": 12,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Orderflow / setups (Discovery)",
    "workingTitle": "Absorption",
    "hookLine": "When price hits a wall and big players eat every sell — that's absorption.",
    "contentBrief": "When price hits a wall and big players eat every sell — that's absorption.",
    "cta": "Follow for the order flow no one teaches • Save",
    "stories": "This-or-that: \"Which is harder: entries or exits?\"",
    "notes": ""
  },
  {
    "day": 81,
    "date": "2026-09-04",
    "weekday": "Fri",
    "week": 12,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Risk & psychology (Shareable)",
    "workingTitle": "It's not your strategy",
    "hookLine": "You're not losing because of your system. It's this.",
    "contentBrief": "You're not losing because of your system. It's this.",
    "cta": "Share with a trader who needs to hear this",
    "stories": "Poll: \"Your biggest leak: revenge / overtrading / no plan?\"",
    "notes": "CONVERT: pin best lead-magnet reel; mention free Telegram/community in Stories"
  },
  {
    "day": 82,
    "date": "2026-09-05",
    "weekday": "Sat",
    "week": 12,
    "phase": "P3 · Compound",
    "format": "Carousel",
    "pillar": "Process & system (Save + Convert)",
    "workingTitle": "My order flow screen layout",
    "hookLine": "Exactly what's on my charts and why.",
    "contentBrief": "Exactly what's on my charts and why.",
    "cta": "Comment \"TAPE\" and I'll DM you the free cheat sheet",
    "stories": "Lead-magnet sticker + weekend deep-dive teaser",
    "notes": ""
  },
  {
    "day": 83,
    "date": "2026-09-06",
    "weekday": "Sun",
    "week": 12,
    "phase": "P3 · Compound",
    "format": "Story only",
    "pillar": "Rest · Repurpose · Review",
    "workingTitle": "Weekly review + repurpose top performer",
    "hookLine": "",
    "contentBrief": "Pull your top 3 posts by reach this week, find the pattern, re-share the best to Stories.",
    "cta": "Weekly recap + \"What should I cover next?\" poll",
    "stories": "Recap carousel/story + \"Next week I'm covering ___\" poll",
    "notes": "MONTH REVIEW: check reach-from-non-followers %, saves, shares, profile-visit→follow"
  },
  {
    "day": 84,
    "date": "2026-09-07",
    "weekday": "Mon",
    "week": 12,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Orderflow basics (Discovery)",
    "workingTitle": "Aggressive vs passive orders",
    "hookLine": "Who actually moves price: the people hitting market, not the ones waiting.",
    "contentBrief": "Who actually moves price: the people hitting market, not the ones waiting.",
    "cta": "Follow for daily NQ order flow • Save this",
    "stories": "Poll: \"Do you trade order flow? Y/N\"",
    "notes": ""
  },
  {
    "day": 85,
    "date": "2026-09-08",
    "weekday": "Tue",
    "week": 13,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Trade breakdown (Proof)",
    "workingTitle": "NQ breakdown — Mean-reversion at value edge",
    "hookLine": "Today's NQ trade, frame by frame: the mean-reversion at value edge the tape called early.",
    "contentBrief": "Break down today's cleanest trade through the mean-reversion at value edge lens. Entry, invalidation, exit.",
    "cta": "Follow — I break down a real trade every session",
    "stories": "Behind-the-scenes of your setup / live marking",
    "notes": ""
  },
  {
    "day": 86,
    "date": "2026-09-09",
    "weekday": "Wed",
    "week": 13,
    "phase": "P3 · Compound",
    "format": "Carousel",
    "pillar": "GEX & options flow (Authority)",
    "workingTitle": "GEX + order flow combo",
    "hookLine": "Levels tell you WHERE, order flow tells you WHEN. Together = my edge.",
    "contentBrief": "Levels tell you WHERE, order flow tells you WHEN. Together = my edge.",
    "cta": "Save this for your next session",
    "stories": "Q&A box: \"Ask me anything about GEX / order flow\"",
    "notes": ""
  },
  {
    "day": 87,
    "date": "2026-09-10",
    "weekday": "Thu",
    "week": 13,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Orderflow / setups (Discovery)",
    "workingTitle": "Support & resistance is lying",
    "hookLine": "Why your S/R lines fail — and what order flow uses instead.",
    "contentBrief": "Why your S/R lines fail — and what order flow uses instead.",
    "cta": "Follow for the order flow no one teaches • Save",
    "stories": "This-or-that: \"Which is harder: entries or exits?\"",
    "notes": ""
  },
  {
    "day": 88,
    "date": "2026-09-11",
    "weekday": "Fri",
    "week": 13,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Risk & psychology (Shareable)",
    "workingTitle": "Revenge trading",
    "hookLine": "How one bad trade turns into five — and how to break the loop.",
    "contentBrief": "How one bad trade turns into five — and how to break the loop.",
    "cta": "Share with a trader who needs to hear this",
    "stories": "Poll: \"Your biggest leak: revenge / overtrading / no plan?\"",
    "notes": "CONVERT: pin best lead-magnet reel; mention free Telegram/community in Stories"
  },
  {
    "day": 89,
    "date": "2026-09-12",
    "weekday": "Sat",
    "week": 13,
    "phase": "P3 · Compound",
    "format": "Carousel",
    "pillar": "Process & system (Save + Convert)",
    "workingTitle": "My pre-market routine",
    "hookLine": "The exact 4 steps I run before I touch NQ. Steal it.",
    "contentBrief": "The exact 4 steps I run before I touch NQ. Steal it.",
    "cta": "Comment \"ROUTINE\" and I'll DM you the free cheat sheet",
    "stories": "Lead-magnet sticker + weekend deep-dive teaser",
    "notes": ""
  },
  {
    "day": 90,
    "date": "2026-09-13",
    "weekday": "Sun",
    "week": 13,
    "phase": "P3 · Compound",
    "format": "Story only",
    "pillar": "Rest · Repurpose · Review",
    "workingTitle": "Weekly review + repurpose top performer",
    "hookLine": "",
    "contentBrief": "Pull your top 3 posts by reach this week, find the pattern, re-share the best to Stories.",
    "cta": "Weekly recap + \"What should I cover next?\" poll",
    "stories": "Recap carousel/story + \"Next week I'm covering ___\" poll",
    "notes": ""
  },
  {
    "day": 91,
    "date": "2026-09-14",
    "weekday": "Mon",
    "week": 13,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Orderflow basics (Discovery)",
    "workingTitle": "The footprint chart",
    "hookLine": "How to read a footprint candle without drowning in numbers.",
    "contentBrief": "How to read a footprint candle without drowning in numbers.",
    "cta": "Follow for daily NQ order flow • Save this",
    "stories": "Poll: \"Do you trade order flow? Y/N\"",
    "notes": ""
  },
  {
    "day": 92,
    "date": "2026-09-15",
    "weekday": "Tue",
    "week": 14,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Trade breakdown (Proof)",
    "workingTitle": "NQ breakdown — Squeeze play",
    "hookLine": "Today's NQ trade, frame by frame: the squeeze play the tape called early.",
    "contentBrief": "Break down today's cleanest trade through the squeeze play lens. Entry, invalidation, exit.",
    "cta": "Follow — I break down a real trade every session",
    "stories": "Behind-the-scenes of your setup / live marking",
    "notes": ""
  },
  {
    "day": 93,
    "date": "2026-09-16",
    "weekday": "Wed",
    "week": 14,
    "phase": "P3 · Compound",
    "format": "Carousel",
    "pillar": "GEX & options flow (Authority)",
    "workingTitle": "Balanced vs imbalanced days",
    "hookLine": "How to tell if the market wants to range or run.",
    "contentBrief": "How to tell if the market wants to range or run.",
    "cta": "Save this for your next session",
    "stories": "Q&A box: \"Ask me anything about GEX / order flow\"",
    "notes": ""
  },
  {
    "day": 94,
    "date": "2026-09-17",
    "weekday": "Thu",
    "week": 14,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Orderflow / setups (Discovery)",
    "workingTitle": "CVD (cumulative volume delta)",
    "hookLine": "Following the real buying pressure under the price.",
    "contentBrief": "Following the real buying pressure under the price.",
    "cta": "Follow for the order flow no one teaches • Save",
    "stories": "This-or-that: \"Which is harder: entries or exits?\"",
    "notes": ""
  },
  {
    "day": 95,
    "date": "2026-09-18",
    "weekday": "Fri",
    "week": 14,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Risk & psychology (Shareable)",
    "workingTitle": "Process over P&L",
    "hookLine": "Why I judge my day on execution, not the dollar number.",
    "contentBrief": "Why I judge my day on execution, not the dollar number.",
    "cta": "Share with a trader who needs to hear this",
    "stories": "Poll: \"Your biggest leak: revenge / overtrading / no plan?\"",
    "notes": "CONVERT: pin best lead-magnet reel; mention free Telegram/community in Stories"
  },
  {
    "day": 96,
    "date": "2026-09-19",
    "weekday": "Sat",
    "week": 14,
    "phase": "P3 · Compound",
    "format": "Carousel",
    "pillar": "Process & system (Save + Convert)",
    "workingTitle": "1-page pre-entry checklist",
    "hookLine": "The checklist I run before every single entry.",
    "contentBrief": "The checklist I run before every single entry.",
    "cta": "Comment \"TAPE\" and I'll DM you the free cheat sheet",
    "stories": "Lead-magnet sticker + weekend deep-dive teaser",
    "notes": ""
  },
  {
    "day": 97,
    "date": "2026-09-20",
    "weekday": "Sun",
    "week": 14,
    "phase": "P3 · Compound",
    "format": "Story only",
    "pillar": "Rest · Repurpose · Review",
    "workingTitle": "Weekly review + repurpose top performer",
    "hookLine": "",
    "contentBrief": "Pull your top 3 posts by reach this week, find the pattern, re-share the best to Stories.",
    "cta": "Weekly recap + \"What should I cover next?\" poll",
    "stories": "Recap carousel/story + \"Next week I'm covering ___\" poll",
    "notes": ""
  },
  {
    "day": 98,
    "date": "2026-09-21",
    "weekday": "Mon",
    "week": 14,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Orderflow basics (Discovery)",
    "workingTitle": "Initial Balance",
    "hookLine": "The first hour writes the day's script — here's how to read it.",
    "contentBrief": "The first hour writes the day's script — here's how to read it.",
    "cta": "Follow for daily NQ order flow • Save this",
    "stories": "Poll: \"Do you trade order flow? Y/N\"",
    "notes": ""
  },
  {
    "day": 99,
    "date": "2026-09-22",
    "weekday": "Tue",
    "week": 15,
    "phase": "P3 · Compound",
    "format": "Reel",
    "pillar": "Trade breakdown (Proof)",
    "workingTitle": "NQ breakdown — ORB + IVB filter",
    "hookLine": "Today's NQ trade, frame by frame: the orb + ivb filter the tape called early.",
    "contentBrief": "Break down today's cleanest trade through the orb + ivb filter lens. Entry, invalidation, exit.",
    "cta": "Follow — I break down a real trade every session",
    "stories": "Behind-the-scenes of your setup / live marking",
    "notes": ""
  },
  {
    "day": 100,
    "date": "2026-09-23",
    "weekday": "Wed",
    "week": 15,
    "phase": "P3 · Compound",
    "format": "Carousel",
    "pillar": "GEX & options flow (Authority)",
    "workingTitle": "Why NQ rejects the same level",
    "hookLine": "Same level, same time, every morning — it's not random. It's GEX.",
    "contentBrief": "Same level, same time, every morning — it's not random. It's GEX.",
    "cta": "Save this for your next session",
    "stories": "Q&A box: \"Ask me anything about GEX / order flow\"",
    "notes": ""
  }
];
