// AUTO-GENERATED from tiktok-100-day-cadence.csv — do not edit by hand.
export interface RawTiktokDay {
  day: number;
  date: string;
  weekday: string;
  week: number;
  phase: string;
  action: string;
  content: string;
  note: string;
  overlay: string;
}

export const TIKTOK_100: RawTiktokDay[] = [
  {
    "day": 1,
    "date": "2026-06-16",
    "weekday": "Tue",
    "week": 1,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "NQ breakdown — Triple A (AAA) setup",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "WARM-UP: ease in ~4 posts/wk, NO links in bio/caption yet, build trust"
  },
  {
    "day": 2,
    "date": "2026-06-17",
    "weekday": "Wed",
    "week": 1,
    "phase": "P1 · Ignition",
    "action": "TikTok-native slot",
    "content": "Trending sound + one-line order flow take (15s)",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": "WARM-UP: ease in ~4 posts/wk, NO links in bio/caption yet, build trust"
  },
  {
    "day": 3,
    "date": "2026-06-18",
    "weekday": "Thu",
    "week": 1,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "What is order flow? (the 60-sec version)",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "WARM-UP: ease in ~4 posts/wk, NO links in bio/caption yet, build trust"
  },
  {
    "day": 4,
    "date": "2026-06-19",
    "weekday": "Fri",
    "week": 1,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "Asymmetrical R:R",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "WARM-UP: ease in ~4 posts/wk, NO links in bio/caption yet, build trust"
  },
  {
    "day": 5,
    "date": "2026-06-20",
    "weekday": "Sat",
    "week": 1,
    "phase": "P1 · Ignition",
    "action": "TikTok-native slot",
    "content": "Stitch/duet a bigger trader's clip with your read",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": "WARM-UP: ease in ~4 posts/wk, NO links in bio/caption yet, build trust"
  },
  {
    "day": 6,
    "date": "2026-06-21",
    "weekday": "Sun",
    "week": 1,
    "phase": "P1 · Ignition",
    "action": "Rest · engage · review",
    "content": "No post. 15 min commenting on niche creators; check Account Status for flags.",
    "note": "Pull your top 3 by views, find the pattern, plan next week",
    "overlay": ""
  },
  {
    "day": 7,
    "date": "2026-06-22",
    "weekday": "Mon",
    "week": 1,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "Value Area explained",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "WARM-UP: ease in ~4 posts/wk, NO links in bio/caption yet, build trust"
  },
  {
    "day": 8,
    "date": "2026-06-23",
    "weekday": "Tue",
    "week": 2,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "NQ breakdown — Trend-following entry",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "WARM-UP: ease in ~4 posts/wk, NO links in bio/caption yet, build trust"
  },
  {
    "day": 9,
    "date": "2026-06-24",
    "weekday": "Wed",
    "week": 2,
    "phase": "P1 · Ignition",
    "action": "TikTok-native slot",
    "content": "Quick market reaction: what NQ did today, 15s",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": "WARM-UP: ease in ~4 posts/wk, NO links in bio/caption yet, build trust"
  },
  {
    "day": 10,
    "date": "2026-06-25",
    "weekday": "Thu",
    "week": 2,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "Point of Control (POC)",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "WARM-UP: ease in ~4 posts/wk, NO links in bio/caption yet, build trust"
  },
  {
    "day": 11,
    "date": "2026-06-26",
    "weekday": "Fri",
    "week": 2,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "Stop-loss discipline",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "WARM-UP: ease in ~4 posts/wk, NO links in bio/caption yet, build trust"
  },
  {
    "day": 12,
    "date": "2026-06-27",
    "weekday": "Sat",
    "week": 2,
    "phase": "P1 · Ignition",
    "action": "TikTok-native slot",
    "content": "Myth-bust a common retail belief in a trend format",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": "WARM-UP: ease in ~4 posts/wk, NO links in bio/caption yet, build trust"
  },
  {
    "day": 13,
    "date": "2026-06-28",
    "weekday": "Sun",
    "week": 2,
    "phase": "P1 · Ignition",
    "action": "Rest · engage · review",
    "content": "No post. 15 min commenting on niche creators; check Account Status for flags.",
    "note": "Pull your top 3 by views, find the pattern, plan next week",
    "overlay": ""
  },
  {
    "day": 14,
    "date": "2026-06-29",
    "weekday": "Mon",
    "week": 2,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "Volume Delta in 60 seconds",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "WARM-UP: ease in ~4 posts/wk, NO links in bio/caption yet, build trust"
  },
  {
    "day": 15,
    "date": "2026-06-30",
    "weekday": "Tue",
    "week": 3,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "NQ breakdown — Mean-reversion at value edge",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 16,
    "date": "2026-07-01",
    "weekday": "Wed",
    "week": 3,
    "phase": "P1 · Ignition",
    "action": "TikTok-native slot",
    "content": "Behind-the-scenes: your screen setup, fast cuts",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 17,
    "date": "2026-07-02",
    "weekday": "Thu",
    "week": 3,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "Absorption",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 18,
    "date": "2026-07-03",
    "weekday": "Fri",
    "week": 3,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "Trailing profits",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 19,
    "date": "2026-07-04",
    "weekday": "Sat",
    "week": 3,
    "phase": "P1 · Ignition",
    "action": "TikTok-native slot",
    "content": "Answer a top comment as a short video (Q&A)",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 20,
    "date": "2026-07-05",
    "weekday": "Sun",
    "week": 3,
    "phase": "P1 · Ignition",
    "action": "Rest · engage · review",
    "content": "No post. 15 min commenting on niche creators; check Account Status for flags.",
    "note": "Pull your top 3 by views, find the pattern, plan next week",
    "overlay": ""
  },
  {
    "day": 21,
    "date": "2026-07-06",
    "weekday": "Mon",
    "week": 3,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "Aggressive vs passive orders",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 22,
    "date": "2026-07-07",
    "weekday": "Tue",
    "week": 4,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "NQ breakdown — Squeeze play",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 23,
    "date": "2026-07-08",
    "weekday": "Wed",
    "week": 4,
    "phase": "P1 · Ignition",
    "action": "TikTok-native slot",
    "content": "Green-screen a chart and talk over it (trend format)",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 24,
    "date": "2026-07-09",
    "weekday": "Thu",
    "week": 4,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "Support & resistance is lying",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 25,
    "date": "2026-07-10",
    "weekday": "Fri",
    "week": 4,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "Daily loss limit",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 26,
    "date": "2026-07-11",
    "weekday": "Sat",
    "week": 4,
    "phase": "P1 · Ignition",
    "action": "TikTok-native slot",
    "content": "POV/relatable trader moment in a trending format",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 27,
    "date": "2026-07-12",
    "weekday": "Sun",
    "week": 4,
    "phase": "P1 · Ignition",
    "action": "Rest · engage · review",
    "content": "No post. 15 min commenting on niche creators; check Account Status for flags.",
    "note": "Pull your top 3 by views, find the pattern, plan next week",
    "overlay": "MONTH REVIEW: FYP reach %, watch-time, shares, follows"
  },
  {
    "day": 28,
    "date": "2026-07-13",
    "weekday": "Mon",
    "week": 4,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "The footprint chart",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 29,
    "date": "2026-07-14",
    "weekday": "Tue",
    "week": 5,
    "phase": "P1 · Ignition",
    "action": "Repost native (clean export)",
    "content": "NQ breakdown — ORB + IVB filter",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 30,
    "date": "2026-07-15",
    "weekday": "Wed",
    "week": 5,
    "phase": "P1 · Ignition",
    "action": "TikTok-native slot",
    "content": "Trending sound + one-line order flow take (15s)",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 31,
    "date": "2026-07-16",
    "weekday": "Thu",
    "week": 5,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "CVD (cumulative volume delta)",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 32,
    "date": "2026-07-17",
    "weekday": "Fri",
    "week": 5,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "Size down on chop",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 33,
    "date": "2026-07-18",
    "weekday": "Sat",
    "week": 5,
    "phase": "P2 · Authority",
    "action": "TikTok-native slot",
    "content": "Stitch/duet a bigger trader's clip with your read",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 34,
    "date": "2026-07-19",
    "weekday": "Sun",
    "week": 5,
    "phase": "P2 · Authority",
    "action": "Rest · engage · review",
    "content": "No post. 15 min commenting on niche creators; check Account Status for flags.",
    "note": "Pull your top 3 by views, find the pattern, plan next week",
    "overlay": ""
  },
  {
    "day": 35,
    "date": "2026-07-20",
    "weekday": "Mon",
    "week": 5,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "Initial Balance",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "COLLAB: stitch/duet or DM a same-size SA trader"
  },
  {
    "day": 36,
    "date": "2026-07-21",
    "weekday": "Tue",
    "week": 6,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "NQ breakdown — Absorption reversal",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 37,
    "date": "2026-07-22",
    "weekday": "Wed",
    "week": 6,
    "phase": "P2 · Authority",
    "action": "TikTok-native slot",
    "content": "Quick market reaction: what NQ did today, 15s",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 38,
    "date": "2026-07-23",
    "weekday": "Thu",
    "week": 6,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "Stacked imbalances",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 39,
    "date": "2026-07-24",
    "weekday": "Fri",
    "week": 6,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "Profit recycling",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 40,
    "date": "2026-07-25",
    "weekday": "Sat",
    "week": 6,
    "phase": "P2 · Authority",
    "action": "TikTok-native slot",
    "content": "Myth-bust a common retail belief in a trend format",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 41,
    "date": "2026-07-26",
    "weekday": "Sun",
    "week": 6,
    "phase": "P2 · Authority",
    "action": "Rest · engage · review",
    "content": "No post. 15 min commenting on niche creators; check Account Status for flags.",
    "note": "Pull your top 3 by views, find the pattern, plan next week",
    "overlay": ""
  },
  {
    "day": 42,
    "date": "2026-07-27",
    "weekday": "Mon",
    "week": 6,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "Liquidity & stop hunts",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "COLLAB: stitch/duet or DM a same-size SA trader"
  },
  {
    "day": 43,
    "date": "2026-07-28",
    "weekday": "Tue",
    "week": 7,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "NQ breakdown — POC rejection",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 44,
    "date": "2026-07-29",
    "weekday": "Wed",
    "week": 7,
    "phase": "P2 · Authority",
    "action": "TikTok-native slot",
    "content": "Behind-the-scenes: your screen setup, fast cuts",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 45,
    "date": "2026-07-30",
    "weekday": "Thu",
    "week": 7,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "Single-day profiling",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 46,
    "date": "2026-07-31",
    "weekday": "Fri",
    "week": 7,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "The trade that blew my account",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 47,
    "date": "2026-08-01",
    "weekday": "Sat",
    "week": 7,
    "phase": "P2 · Authority",
    "action": "TikTok-native slot",
    "content": "Answer a top comment as a short video (Q&A)",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 48,
    "date": "2026-08-02",
    "weekday": "Sun",
    "week": 7,
    "phase": "P2 · Authority",
    "action": "Rest · engage · review",
    "content": "No post. 15 min commenting on niche creators; check Account Status for flags.",
    "note": "Pull your top 3 by views, find the pattern, plan next week",
    "overlay": ""
  },
  {
    "day": 49,
    "date": "2026-08-03",
    "weekday": "Mon",
    "week": 7,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "Composite profiles",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "COLLAB: stitch/duet or DM a same-size SA trader"
  },
  {
    "day": 50,
    "date": "2026-08-04",
    "weekday": "Tue",
    "week": 8,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "NQ breakdown — Gamma-level fade",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 51,
    "date": "2026-08-05",
    "weekday": "Wed",
    "week": 8,
    "phase": "P2 · Authority",
    "action": "TikTok-native slot",
    "content": "Green-screen a chart and talk over it (trend format)",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 52,
    "date": "2026-08-06",
    "weekday": "Thu",
    "week": 8,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "Trend day vs chop day",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 53,
    "date": "2026-08-07",
    "weekday": "Fri",
    "week": 8,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "Ego management",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 54,
    "date": "2026-08-08",
    "weekday": "Sat",
    "week": 8,
    "phase": "P2 · Authority",
    "action": "TikTok-native slot",
    "content": "POV/relatable trader moment in a trending format",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 55,
    "date": "2026-08-09",
    "weekday": "Sun",
    "week": 8,
    "phase": "P2 · Authority",
    "action": "Rest · engage · review",
    "content": "No post. 15 min commenting on niche creators; check Account Status for flags.",
    "note": "Pull your top 3 by views, find the pattern, plan next week",
    "overlay": "MONTH REVIEW: FYP reach %, watch-time, shares, follows"
  },
  {
    "day": 56,
    "date": "2026-08-10",
    "weekday": "Mon",
    "week": 8,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "Opening Range Breakout (ORB)",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "COLLAB: stitch/duet or DM a same-size SA trader"
  },
  {
    "day": 57,
    "date": "2026-08-11",
    "weekday": "Tue",
    "week": 9,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "NQ breakdown — Failed breakout trap",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 58,
    "date": "2026-08-12",
    "weekday": "Wed",
    "week": 9,
    "phase": "P2 · Authority",
    "action": "TikTok-native slot",
    "content": "Trending sound + one-line order flow take (15s)",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 59,
    "date": "2026-08-13",
    "weekday": "Thu",
    "week": 9,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "Deep Effort / effort vs result",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 60,
    "date": "2026-08-14",
    "weekday": "Fri",
    "week": 9,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "Accepting losses",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 61,
    "date": "2026-08-15",
    "weekday": "Sat",
    "week": 9,
    "phase": "P2 · Authority",
    "action": "TikTok-native slot",
    "content": "Stitch/duet a bigger trader's clip with your read",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 62,
    "date": "2026-08-16",
    "weekday": "Sun",
    "week": 9,
    "phase": "P2 · Authority",
    "action": "Rest · engage · review",
    "content": "No post. 15 min commenting on niche creators; check Account Status for flags.",
    "note": "Pull your top 3 by views, find the pattern, plan next week",
    "overlay": ""
  },
  {
    "day": 63,
    "date": "2026-08-17",
    "weekday": "Mon",
    "week": 9,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "IVB (initial volume bias)",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "COLLAB: stitch/duet or DM a same-size SA trader"
  },
  {
    "day": 64,
    "date": "2026-08-18",
    "weekday": "Tue",
    "week": 10,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "NQ breakdown — CVD divergence entry",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 65,
    "date": "2026-08-19",
    "weekday": "Wed",
    "week": 10,
    "phase": "P2 · Authority",
    "action": "TikTok-native slot",
    "content": "Quick market reaction: what NQ did today, 15s",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 66,
    "date": "2026-08-20",
    "weekday": "Thu",
    "week": 10,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "What is order flow? (the 60-sec version)",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 67,
    "date": "2026-08-21",
    "weekday": "Fri",
    "week": 10,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "Patience",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 68,
    "date": "2026-08-22",
    "weekday": "Sat",
    "week": 10,
    "phase": "P2 · Authority",
    "action": "TikTok-native slot",
    "content": "Myth-bust a common retail belief in a trend format",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 69,
    "date": "2026-08-23",
    "weekday": "Sun",
    "week": 10,
    "phase": "P2 · Authority",
    "action": "Rest · engage · review",
    "content": "No post. 15 min commenting on niche creators; check Account Status for flags.",
    "note": "Pull your top 3 by views, find the pattern, plan next week",
    "overlay": ""
  },
  {
    "day": 70,
    "date": "2026-08-24",
    "weekday": "Mon",
    "week": 10,
    "phase": "P2 · Authority",
    "action": "Repost native (clean export)",
    "content": "Value Area explained",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "COLLAB: stitch/duet or DM a same-size SA trader"
  },
  {
    "day": 71,
    "date": "2026-08-25",
    "weekday": "Tue",
    "week": 11,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "NQ breakdown — Triple A (AAA) setup",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 72,
    "date": "2026-08-26",
    "weekday": "Wed",
    "week": 11,
    "phase": "P3 · Compound",
    "action": "TikTok-native slot",
    "content": "Behind-the-scenes: your screen setup, fast cuts",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 73,
    "date": "2026-08-27",
    "weekday": "Thu",
    "week": 11,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "Point of Control (POC)",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 74,
    "date": "2026-08-28",
    "weekday": "Fri",
    "week": 11,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "3 order flow traps",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "CONVERT: now safe to add bio link to IG/Discord"
  },
  {
    "day": 75,
    "date": "2026-08-29",
    "weekday": "Sat",
    "week": 11,
    "phase": "P3 · Compound",
    "action": "TikTok-native slot",
    "content": "Answer a top comment as a short video (Q&A)",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 76,
    "date": "2026-08-30",
    "weekday": "Sun",
    "week": 11,
    "phase": "P3 · Compound",
    "action": "Rest · engage · review",
    "content": "No post. 15 min commenting on niche creators; check Account Status for flags.",
    "note": "Pull your top 3 by views, find the pattern, plan next week",
    "overlay": ""
  },
  {
    "day": 77,
    "date": "2026-08-31",
    "weekday": "Mon",
    "week": 11,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "Volume Delta in 60 seconds",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 78,
    "date": "2026-09-01",
    "weekday": "Tue",
    "week": 12,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "NQ breakdown — Trend-following entry",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 79,
    "date": "2026-09-02",
    "weekday": "Wed",
    "week": 12,
    "phase": "P3 · Compound",
    "action": "TikTok-native slot",
    "content": "Green-screen a chart and talk over it (trend format)",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 80,
    "date": "2026-09-03",
    "weekday": "Thu",
    "week": 12,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "Absorption",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 81,
    "date": "2026-09-04",
    "weekday": "Fri",
    "week": 12,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "It's not your strategy",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "CONVERT: now safe to add bio link to IG/Discord"
  },
  {
    "day": 82,
    "date": "2026-09-05",
    "weekday": "Sat",
    "week": 12,
    "phase": "P3 · Compound",
    "action": "TikTok-native slot",
    "content": "POV/relatable trader moment in a trending format",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 83,
    "date": "2026-09-06",
    "weekday": "Sun",
    "week": 12,
    "phase": "P3 · Compound",
    "action": "Rest · engage · review",
    "content": "No post. 15 min commenting on niche creators; check Account Status for flags.",
    "note": "Pull your top 3 by views, find the pattern, plan next week",
    "overlay": "MONTH REVIEW: FYP reach %, watch-time, shares, follows"
  },
  {
    "day": 84,
    "date": "2026-09-07",
    "weekday": "Mon",
    "week": 12,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "Aggressive vs passive orders",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 85,
    "date": "2026-09-08",
    "weekday": "Tue",
    "week": 13,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "NQ breakdown — Mean-reversion at value edge",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 86,
    "date": "2026-09-09",
    "weekday": "Wed",
    "week": 13,
    "phase": "P3 · Compound",
    "action": "TikTok-native slot",
    "content": "Trending sound + one-line order flow take (15s)",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 87,
    "date": "2026-09-10",
    "weekday": "Thu",
    "week": 13,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "Support & resistance is lying",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 88,
    "date": "2026-09-11",
    "weekday": "Fri",
    "week": 13,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "Revenge trading",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "CONVERT: now safe to add bio link to IG/Discord"
  },
  {
    "day": 89,
    "date": "2026-09-12",
    "weekday": "Sat",
    "week": 13,
    "phase": "P3 · Compound",
    "action": "TikTok-native slot",
    "content": "Stitch/duet a bigger trader's clip with your read",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 90,
    "date": "2026-09-13",
    "weekday": "Sun",
    "week": 13,
    "phase": "P3 · Compound",
    "action": "Rest · engage · review",
    "content": "No post. 15 min commenting on niche creators; check Account Status for flags.",
    "note": "Pull your top 3 by views, find the pattern, plan next week",
    "overlay": ""
  },
  {
    "day": 91,
    "date": "2026-09-14",
    "weekday": "Mon",
    "week": 13,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "The footprint chart",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 92,
    "date": "2026-09-15",
    "weekday": "Tue",
    "week": 14,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "NQ breakdown — Squeeze play",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 93,
    "date": "2026-09-16",
    "weekday": "Wed",
    "week": 14,
    "phase": "P3 · Compound",
    "action": "TikTok-native slot",
    "content": "Quick market reaction: what NQ did today, 15s",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 94,
    "date": "2026-09-17",
    "weekday": "Thu",
    "week": 14,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "CVD (cumulative volume delta)",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 95,
    "date": "2026-09-18",
    "weekday": "Fri",
    "week": 14,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "Process over P&L",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": "CONVERT: now safe to add bio link to IG/Discord"
  },
  {
    "day": 96,
    "date": "2026-09-19",
    "weekday": "Sat",
    "week": 14,
    "phase": "P3 · Compound",
    "action": "TikTok-native slot",
    "content": "Myth-bust a common retail belief in a trend format",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  },
  {
    "day": 97,
    "date": "2026-09-20",
    "weekday": "Sun",
    "week": 14,
    "phase": "P3 · Compound",
    "action": "Rest · engage · review",
    "content": "No post. 15 min commenting on niche creators; check Account Status for flags.",
    "note": "Pull your top 3 by views, find the pattern, plan next week",
    "overlay": ""
  },
  {
    "day": 98,
    "date": "2026-09-21",
    "weekday": "Mon",
    "week": 14,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "Initial Balance",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 99,
    "date": "2026-09-22",
    "weekday": "Tue",
    "week": 15,
    "phase": "P3 · Compound",
    "action": "Repost native (clean export)",
    "content": "NQ breakdown — ORB + IVB filter",
    "note": "Use the clean iPhone export (no IG watermark) • fresh TikTok caption + trending sound • hook in first 1s",
    "overlay": ""
  },
  {
    "day": 100,
    "date": "2026-09-23",
    "weekday": "Wed",
    "week": 15,
    "phase": "P3 · Compound",
    "action": "TikTok-native slot",
    "content": "Behind-the-scenes: your screen setup, fast cuts",
    "note": "TikTok-only (carousels stay on IG) • lean into a trend/sound • keep it raw and fast",
    "overlay": ""
  }
];
